// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { GongShapeDB } from '../gongshape-db'
import { GongShapeService } from '../gongshape.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-gongshape-sorting',
  templateUrl: './gongshape-sorting.component.html',
  styleUrls: ['./gongshape-sorting.component.css']
})
export class GongShapeSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of GongShape instances that are in the association
  associatedGongShapes = new Array<GongShapeDB>();

  constructor(
    private gongshapeService: GongShapeService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of gongshape instances
    public dialogRef: MatDialogRef<GongShapeSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getGongShapes()
  }

  getGongShapes(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let gongshape of this.frontRepo.GongShapes_array) {
          let ID = this.dialogData.ID
          let revPointerID = gongshape[this.dialogData.ReversePointer as keyof GongShapeDB] as unknown as NullInt64
          let revPointerID_Index = gongshape[this.dialogData.ReversePointer + "_Index" as keyof GongShapeDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedGongShapes.push(gongshape)
          }
        }

        // sort associated gongshape according to order
        this.associatedGongShapes.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedGongShapes, event.previousIndex, event.currentIndex);

    // set the order of GongShape instances
    let index = 0

    for (let gongshape of this.associatedGongShapes) {
      let revPointerID_Index = gongshape[this.dialogData.ReversePointer + "_Index" as keyof GongShapeDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedGongShapes.forEach(
      gongshape => {
        this.gongshapeService.updateGongShape(gongshape, this.dialogData.GONG__StackPath)
          .subscribe(gongshape => {
            this.gongshapeService.GongShapeServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
