// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { LinkDB } from '../link-db'
import { LinkService } from '../link.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-linkstable',
  templateUrl: './links-table.component.html',
  styleUrls: ['./links-table.component.css'],
})
export class LinksTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of Link instances
  selection: SelectionModel<LinkDB>;
  initialSelection = new Array<LinkDB>();

  // the data source for the table
  links: LinkDB[];
  matTableDataSource: MatTableDataSource<LinkDB>

  // front repo, that will be referenced by this.links
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (linkDB: LinkDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return linkDB.Name;

        case 'Fieldname':
          return linkDB.Fieldname;

        case 'Structname':
          return linkDB.Structname;

        case 'Fieldtypename':
          return linkDB.Fieldtypename;

        case 'Multiplicity':
          return linkDB.Multiplicity;

        case 'Middlevertice':
          return (linkDB.Middlevertice ? linkDB.Middlevertice.Name : '');

        case 'Links':
          return this.frontRepo.Classshapes.get(linkDB.Classshape_LinksDBID.Int64)?.Name;

        default:
          return LinkDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (linkDB: LinkDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the linkDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += linkDB.Name.toLowerCase()
      mergedContent += linkDB.Fieldname.toLowerCase()
      mergedContent += linkDB.Structname.toLowerCase()
      mergedContent += linkDB.Fieldtypename.toLowerCase()
      mergedContent += linkDB.Multiplicity.toLowerCase()
      if (linkDB.Middlevertice) {
        mergedContent += linkDB.Middlevertice.Name.toLowerCase()
      }
      if (linkDB.Classshape_LinksDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Classshapes.get(linkDB.Classshape_LinksDBID.Int64)?.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private linkService: LinkService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of link instances
    public dialogRef: MatDialogRef<LinksTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.linkService.LinkServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getLinks()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Fieldname",
        "Structname",
        "Fieldtypename",
        "Multiplicity",
        "Middlevertice",
        "Links",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Fieldname",
        "Structname",
        "Fieldtypename",
        "Multiplicity",
        "Middlevertice",
        "Links",
      ]
      this.selection = new SelectionModel<LinkDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getLinks()
    this.matTableDataSource = new MatTableDataSource(this.links)
  }

  getLinks(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.links = this.frontRepo.Links_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.links.forEach(
            link => {
              let ID = this.dialogData.ID
              let revPointer = link[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(link)
              }
            }
          )
          this.selection = new SelectionModel<LinkDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let link = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(link)
            }
          }
          this.selection = new SelectionModel<LinkDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.links
      }
    )
  }

  // newLink initiate a new link
  // create a new Link objet
  newLink() {
  }

  deleteLink(linkID: number, link: LinkDB) {
    // list of links is truncated of link before the delete
    this.links = this.links.filter(h => h !== link);

    this.linkService.deleteLink(linkID).subscribe(
      link => {
        this.linkService.LinkServiceChanged.next("delete")
      }
    );
  }

  editLink(linkID: number, link: LinkDB) {

  }

  // display link in router
  displayLinkInRouter(linkID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongdoc_go-" + "link-display", linkID])
  }

  // set editor outlet
  setEditorRouterOutlet(linkID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_editor: ["github_com_fullstack_lang_gongdoc_go-" + "link-detail", linkID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(linkID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_presentation: ["github_com_fullstack_lang_gongdoc_go-" + "link-presentation", linkID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.links.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.links.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<LinkDB>()

      // reset all initial selection of link that belong to link
      this.initialSelection.forEach(
        link => {
          link[this.dialogData.ReversePointer].Int64 = 0
          link[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(link)
        }
      )

      // from selection, set link that belong to link
      this.selection.selected.forEach(
        link => {
          let ID = +this.dialogData.ID
          link[this.dialogData.ReversePointer].Int64 = ID
          link[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(link)
        }
      )

      // update all link (only update selection & initial selection)
      toUpdate.forEach(
        link => {
          this.linkService.updateLink(link)
            .subscribe(link => {
              this.linkService.LinkServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedLink = new Set<number>()
      for (let link of this.initialSelection) {
        if (this.selection.selected.includes(link)) {
          // console.log("link " + link.Name + " is still selected")
        } else {
          console.log("link " + link.Name + " has been unselected")
          unselectedLink.add(link.ID)
          console.log("is unselected " + unselectedLink.has(link.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let link = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedLink.has(link.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          link => {
            if (!this.initialSelection.includes(link)) {
              // console.log("link " + link.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + link.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = link.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("link " + link.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<LinkDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
