// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { GongdocCommandDB } from '../gongdoccommand-db'
import { GongdocCommandService } from '../gongdoccommand.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-gongdoccommands-table',
  templateUrl: './gongdoccommands-table.component.html',
  styleUrls: ['./gongdoccommands-table.component.css'],
})
export class GongdocCommandsTableComponent implements OnInit {

  // used if the component is called as a selection component of GongdocCommand instances
  selection: SelectionModel<GongdocCommandDB>;
  initialSelection = new Array<GongdocCommandDB>();

  // the data source for the table
  gongdoccommands: GongdocCommandDB[];
  matTableDataSource: MatTableDataSource<GongdocCommandDB>


  // front repo, that will be referenced by this.gongdoccommands
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private gongdoccommandService: GongdocCommandService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of gongdoccommand instances
    public dialogRef: MatDialogRef<GongdocCommandsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.gongdoccommandService.GongdocCommandServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getGongdocCommands()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Command",
        "DiagramName",
        "Date",
        "GongdocNodeType",
        "StructName",
        "FieldName",
        "FieldTypeName",
        "PositionX",
        "PositionY",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Command",
        "DiagramName",
        "Date",
        "GongdocNodeType",
        "StructName",
        "FieldName",
        "FieldTypeName",
        "PositionX",
        "PositionY",
      ]
      this.selection = new SelectionModel<GongdocCommandDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getGongdocCommands()
    this.matTableDataSource = new MatTableDataSource(this.gongdoccommands)
  }

  getGongdocCommands(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.gongdoccommands = this.frontRepo.GongdocCommands_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.gongdoccommands.forEach(
            gongdoccommand => {
              let ID = this.dialogData.ID
              let revPointer = gongdoccommand[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(gongdoccommand)
              }
            }
          )
          this.selection = new SelectionModel<GongdocCommandDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.gongdoccommands
      }
    )
  }

  // newGongdocCommand initiate a new gongdoccommand
  // create a new GongdocCommand objet
  newGongdocCommand() {
  }

  deleteGongdocCommand(gongdoccommandID: number, gongdoccommand: GongdocCommandDB) {
    // list of gongdoccommands is truncated of gongdoccommand before the delete
    this.gongdoccommands = this.gongdoccommands.filter(h => h !== gongdoccommand);

    this.gongdoccommandService.deleteGongdocCommand(gongdoccommandID).subscribe(
      gongdoccommand => {
        this.gongdoccommandService.GongdocCommandServiceChanged.next("delete")
      }
    );
  }

  editGongdocCommand(gongdoccommandID: number, gongdoccommand: GongdocCommandDB) {

  }

  // display gongdoccommand in router
  displayGongdocCommandInRouter(gongdoccommandID: number) {
    this.router.navigate(["gongdoccommand-display", gongdoccommandID])
  }

  // set editor outlet
  setEditorRouterOutlet(gongdoccommandID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["gongdoccommand-detail", gongdoccommandID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(gongdoccommandID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["gongdoccommand-presentation", gongdoccommandID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.gongdoccommands.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.gongdoccommands.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<GongdocCommandDB>()

    // reset all initial selection of gongdoccommand that belong to gongdoccommand through Anarrayofb
    this.initialSelection.forEach(
      gongdoccommand => {
        gongdoccommand[this.dialogData.ReversePointer].Int64 = 0
        gongdoccommand[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(gongdoccommand)
      }
    )

    // from selection, set gongdoccommand that belong to gongdoccommand through Anarrayofb
    this.selection.selected.forEach(
      gongdoccommand => {
        let ID = +this.dialogData.ID
        gongdoccommand[this.dialogData.ReversePointer].Int64 = ID
        gongdoccommand[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(gongdoccommand)
      }
    )

    // update all gongdoccommand (only update selection & initial selection)
    toUpdate.forEach(
      gongdoccommand => {
        this.gongdoccommandService.updateGongdocCommand(gongdoccommand)
          .subscribe(gongdoccommand => {
            this.gongdoccommandService.GongdocCommandServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
