// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { ClassshapeDB } from '../classshape-db'
import { ClassshapeService } from '../classshape.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-classshapestable',
  templateUrl: './classshapes-table.component.html',
  styleUrls: ['./classshapes-table.component.css'],
})
export class ClassshapesTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of Classshape instances
  selection: SelectionModel<ClassshapeDB>;
  initialSelection = new Array<ClassshapeDB>();

  // the data source for the table
  classshapes: ClassshapeDB[];
  matTableDataSource: MatTableDataSource<ClassshapeDB>

  // front repo, that will be referenced by this.classshapes
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (classshapeDB: ClassshapeDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return classshapeDB.Name;

        case 'Position':
          return (classshapeDB.Position ? classshapeDB.Position.Name : '');

        case 'Structname':
          return classshapeDB.Structname;

        case 'Width':
          return classshapeDB.Width;

        case 'Heigth':
          return classshapeDB.Heigth;

        case 'ClassshapeTargetType':
          return classshapeDB.ClassshapeTargetType;

        case 'Classdiagram_Classshapes':
          return this.frontRepo.Classdiagrams.get(classshapeDB.Classdiagram_ClassshapesDBID.Int64)?.Name;

        default:
          return ClassshapeDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (classshapeDB: ClassshapeDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the classshapeDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += classshapeDB.Name.toLowerCase()
      if (classshapeDB.Position) {
        mergedContent += classshapeDB.Position.Name.toLowerCase()
      }
      mergedContent += classshapeDB.Structname.toLowerCase()
      mergedContent += classshapeDB.Width.toString()
      mergedContent += classshapeDB.Heigth.toString()
      mergedContent += classshapeDB.ClassshapeTargetType.toLowerCase()
      if (classshapeDB.Classdiagram_ClassshapesDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Classdiagrams.get(classshapeDB.Classdiagram_ClassshapesDBID.Int64)?.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private classshapeService: ClassshapeService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of classshape instances
    public dialogRef: MatDialogRef<ClassshapesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.classshapeService.ClassshapeServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getClassshapes()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Position",
        "Structname",
        "Width",
        "Heigth",
        "ClassshapeTargetType",
        "Classdiagram_Classshapes",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Position",
        "Structname",
        "Width",
        "Heigth",
        "ClassshapeTargetType",
        "Classdiagram_Classshapes",
      ]
      this.selection = new SelectionModel<ClassshapeDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getClassshapes()
    this.matTableDataSource = new MatTableDataSource(this.classshapes)
  }

  getClassshapes(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.classshapes = this.frontRepo.Classshapes_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.classshapes.forEach(
            classshape => {
              let ID = this.dialogData.ID
              let revPointer = classshape[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(classshape)
              }
            }
          )
          this.selection = new SelectionModel<ClassshapeDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let classshape = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(classshape)
            }
          }
          this.selection = new SelectionModel<ClassshapeDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.classshapes
      }
    )
  }

  // newClassshape initiate a new classshape
  // create a new Classshape objet
  newClassshape() {
  }

  deleteClassshape(classshapeID: number, classshape: ClassshapeDB) {
    // list of classshapes is truncated of classshape before the delete
    this.classshapes = this.classshapes.filter(h => h !== classshape);

    this.classshapeService.deleteClassshape(classshapeID).subscribe(
      classshape => {
        this.classshapeService.ClassshapeServiceChanged.next("delete")
      }
    );
  }

  editClassshape(classshapeID: number, classshape: ClassshapeDB) {

  }

  // display classshape in router
  displayClassshapeInRouter(classshapeID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongdoc_go-" + "classshape-display", classshapeID])
  }

  // set editor outlet
  setEditorRouterOutlet(classshapeID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_editor: ["github_com_fullstack_lang_gongdoc_go-" + "classshape-detail", classshapeID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(classshapeID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_presentation: ["github_com_fullstack_lang_gongdoc_go-" + "classshape-presentation", classshapeID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.classshapes.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.classshapes.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<ClassshapeDB>()

      // reset all initial selection of classshape that belong to classshape
      this.initialSelection.forEach(
        classshape => {
          classshape[this.dialogData.ReversePointer].Int64 = 0
          classshape[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(classshape)
        }
      )

      // from selection, set classshape that belong to classshape
      this.selection.selected.forEach(
        classshape => {
          let ID = +this.dialogData.ID
          classshape[this.dialogData.ReversePointer].Int64 = ID
          classshape[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(classshape)
        }
      )

      // update all classshape (only update selection & initial selection)
      toUpdate.forEach(
        classshape => {
          this.classshapeService.updateClassshape(classshape)
            .subscribe(classshape => {
              this.classshapeService.ClassshapeServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedClassshape = new Set<number>()
      for (let classshape of this.initialSelection) {
        if (this.selection.selected.includes(classshape)) {
          // console.log("classshape " + classshape.Name + " is still selected")
        } else {
          console.log("classshape " + classshape.Name + " has been unselected")
          unselectedClassshape.add(classshape.ID)
          console.log("is unselected " + unselectedClassshape.has(classshape.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let classshape = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedClassshape.has(classshape.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          classshape => {
            if (!this.initialSelection.includes(classshape)) {
              // console.log("classshape " + classshape.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + classshape.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = classshape.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("classshape " + classshape.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<ClassshapeDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
