// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { GongdocStatusDB } from '../gongdocstatus-db'
import { GongdocStatusService } from '../gongdocstatus.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-gongdocstatusstable',
  templateUrl: './gongdocstatuss-table.component.html',
  styleUrls: ['./gongdocstatuss-table.component.css'],
})
export class GongdocStatussTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of GongdocStatus instances
  selection: SelectionModel<GongdocStatusDB>;
  initialSelection = new Array<GongdocStatusDB>();

  // the data source for the table
  gongdocstatuss: GongdocStatusDB[];
  matTableDataSource: MatTableDataSource<GongdocStatusDB>

  // front repo, that will be referenced by this.gongdocstatuss
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (gongdocstatusDB: GongdocStatusDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return gongdocstatusDB.Name;

        case 'Status':
          return gongdocstatusDB.Status;

        case 'CommandCompletionDate':
          return gongdocstatusDB.CommandCompletionDate;

        default:
          return GongdocStatusDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (gongdocstatusDB: GongdocStatusDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the gongdocstatusDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += gongdocstatusDB.Name.toLowerCase()
      mergedContent += gongdocstatusDB.Status.toLowerCase()
      mergedContent += gongdocstatusDB.CommandCompletionDate.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private gongdocstatusService: GongdocStatusService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of gongdocstatus instances
    public dialogRef: MatDialogRef<GongdocStatussTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.gongdocstatusService.GongdocStatusServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getGongdocStatuss()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Status",
        "CommandCompletionDate",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Status",
        "CommandCompletionDate",
      ]
      this.selection = new SelectionModel<GongdocStatusDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getGongdocStatuss()
    this.matTableDataSource = new MatTableDataSource(this.gongdocstatuss)
  }

  getGongdocStatuss(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.gongdocstatuss = this.frontRepo.GongdocStatuss_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.gongdocstatuss.forEach(
            gongdocstatus => {
              let ID = this.dialogData.ID
              let revPointer = gongdocstatus[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(gongdocstatus)
              }
            }
          )
          this.selection = new SelectionModel<GongdocStatusDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let gongdocstatus = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(gongdocstatus)
            }
          }
          this.selection = new SelectionModel<GongdocStatusDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.gongdocstatuss
      }
    )
  }

  // newGongdocStatus initiate a new gongdocstatus
  // create a new GongdocStatus objet
  newGongdocStatus() {
  }

  deleteGongdocStatus(gongdocstatusID: number, gongdocstatus: GongdocStatusDB) {
    // list of gongdocstatuss is truncated of gongdocstatus before the delete
    this.gongdocstatuss = this.gongdocstatuss.filter(h => h !== gongdocstatus);

    this.gongdocstatusService.deleteGongdocStatus(gongdocstatusID).subscribe(
      gongdocstatus => {
        this.gongdocstatusService.GongdocStatusServiceChanged.next("delete")
      }
    );
  }

  editGongdocStatus(gongdocstatusID: number, gongdocstatus: GongdocStatusDB) {

  }

  // display gongdocstatus in router
  displayGongdocStatusInRouter(gongdocstatusID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongdoc_go-" + "gongdocstatus-display", gongdocstatusID])
  }

  // set editor outlet
  setEditorRouterOutlet(gongdocstatusID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_editor: ["github_com_fullstack_lang_gongdoc_go-" + "gongdocstatus-detail", gongdocstatusID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(gongdocstatusID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_presentation: ["github_com_fullstack_lang_gongdoc_go-" + "gongdocstatus-presentation", gongdocstatusID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.gongdocstatuss.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.gongdocstatuss.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<GongdocStatusDB>()

      // reset all initial selection of gongdocstatus that belong to gongdocstatus
      this.initialSelection.forEach(
        gongdocstatus => {
          gongdocstatus[this.dialogData.ReversePointer].Int64 = 0
          gongdocstatus[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(gongdocstatus)
        }
      )

      // from selection, set gongdocstatus that belong to gongdocstatus
      this.selection.selected.forEach(
        gongdocstatus => {
          let ID = +this.dialogData.ID
          gongdocstatus[this.dialogData.ReversePointer].Int64 = ID
          gongdocstatus[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(gongdocstatus)
        }
      )

      // update all gongdocstatus (only update selection & initial selection)
      toUpdate.forEach(
        gongdocstatus => {
          this.gongdocstatusService.updateGongdocStatus(gongdocstatus)
            .subscribe(gongdocstatus => {
              this.gongdocstatusService.GongdocStatusServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedGongdocStatus = new Set<number>()
      for (let gongdocstatus of this.initialSelection) {
        if (this.selection.selected.includes(gongdocstatus)) {
          // console.log("gongdocstatus " + gongdocstatus.Name + " is still selected")
        } else {
          console.log("gongdocstatus " + gongdocstatus.Name + " has been unselected")
          unselectedGongdocStatus.add(gongdocstatus.ID)
          console.log("is unselected " + unselectedGongdocStatus.has(gongdocstatus.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let gongdocstatus = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedGongdocStatus.has(gongdocstatus.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          gongdocstatus => {
            if (!this.initialSelection.includes(gongdocstatus)) {
              // console.log("gongdocstatus " + gongdocstatus.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + gongdocstatus.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = gongdocstatus.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("gongdocstatus " + gongdocstatus.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<GongdocStatusDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
