// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { ReferenceIdentifierDB } from '../referenceidentifier-db'
import { ReferenceIdentifierService } from '../referenceidentifier.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-referenceidentifierstable',
  templateUrl: './referenceidentifiers-table.component.html',
  styleUrls: ['./referenceidentifiers-table.component.css'],
})
export class ReferenceIdentifiersTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of ReferenceIdentifier instances
  selection: SelectionModel<ReferenceIdentifierDB> = new (SelectionModel)
  initialSelection = new Array<ReferenceIdentifierDB>()

  // the data source for the table
  referenceidentifiers: ReferenceIdentifierDB[] = []
  matTableDataSource: MatTableDataSource<ReferenceIdentifierDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.referenceidentifiers
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (referenceidentifierDB: ReferenceIdentifierDB, property: string) => {
      switch (property) {
        case 'ID':
          return referenceidentifierDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return referenceidentifierDB.Name;

        case 'NbInstances':
          return referenceidentifierDB.NbInstances;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (referenceidentifierDB: ReferenceIdentifierDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the referenceidentifierDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += referenceidentifierDB.Name.toLowerCase()
      mergedContent += referenceidentifierDB.NbInstances.toString()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private referenceidentifierService: ReferenceIdentifierService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of referenceidentifier instances
    public dialogRef: MatDialogRef<ReferenceIdentifiersTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.referenceidentifierService.ReferenceIdentifierServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getReferenceIdentifiers()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "NbInstances",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "NbInstances",
      ]
      this.selection = new SelectionModel<ReferenceIdentifierDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getReferenceIdentifiers()
    this.matTableDataSource = new MatTableDataSource(this.referenceidentifiers)
  }

  getReferenceIdentifiers(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.referenceidentifiers = this.frontRepo.ReferenceIdentifiers_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let referenceidentifier of this.referenceidentifiers) {
            let ID = this.dialogData.ID
            let revPointer = referenceidentifier[this.dialogData.ReversePointer as keyof ReferenceIdentifierDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(referenceidentifier)
            }
            this.selection = new SelectionModel<ReferenceIdentifierDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ReferenceIdentifierDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as ReferenceIdentifierDB[]
          for (let associationInstance of sourceField) {
            let referenceidentifier = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ReferenceIdentifierDB
            this.initialSelection.push(referenceidentifier)
          }

          this.selection = new SelectionModel<ReferenceIdentifierDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.referenceidentifiers
      }
    )
  }

  // newReferenceIdentifier initiate a new referenceidentifier
  // create a new ReferenceIdentifier objet
  newReferenceIdentifier() {
  }

  deleteReferenceIdentifier(referenceidentifierID: number, referenceidentifier: ReferenceIdentifierDB) {
    // list of referenceidentifiers is truncated of referenceidentifier before the delete
    this.referenceidentifiers = this.referenceidentifiers.filter(h => h !== referenceidentifier);

    this.referenceidentifierService.deleteReferenceIdentifier(referenceidentifierID).subscribe(
      referenceidentifier => {
        this.referenceidentifierService.ReferenceIdentifierServiceChanged.next("delete")
      }
    );
  }

  editReferenceIdentifier(referenceidentifierID: number, referenceidentifier: ReferenceIdentifierDB) {

  }

  // display referenceidentifier in router
  displayReferenceIdentifierInRouter(referenceidentifierID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongdoc_go-" + "referenceidentifier-display", referenceidentifierID])
  }

  // set editor outlet
  setEditorRouterOutlet(referenceidentifierID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_editor: ["github_com_fullstack_lang_gongdoc_go-" + "referenceidentifier-detail", referenceidentifierID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(referenceidentifierID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_presentation: ["github_com_fullstack_lang_gongdoc_go-" + "referenceidentifier-presentation", referenceidentifierID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.referenceidentifiers.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.referenceidentifiers.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<ReferenceIdentifierDB>()

      // reset all initial selection of referenceidentifier that belong to referenceidentifier
      for (let referenceidentifier of this.initialSelection) {
        let index = referenceidentifier[this.dialogData.ReversePointer as keyof ReferenceIdentifierDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(referenceidentifier)

      }

      // from selection, set referenceidentifier that belong to referenceidentifier
      for (let referenceidentifier of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = referenceidentifier[this.dialogData.ReversePointer as keyof ReferenceIdentifierDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(referenceidentifier)
      }


      // update all referenceidentifier (only update selection & initial selection)
      for (let referenceidentifier of toUpdate) {
        this.referenceidentifierService.updateReferenceIdentifier(referenceidentifier)
          .subscribe(referenceidentifier => {
            this.referenceidentifierService.ReferenceIdentifierServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ReferenceIdentifierDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedReferenceIdentifier = new Set<number>()
      for (let referenceidentifier of this.initialSelection) {
        if (this.selection.selected.includes(referenceidentifier)) {
          // console.log("referenceidentifier " + referenceidentifier.Name + " is still selected")
        } else {
          console.log("referenceidentifier " + referenceidentifier.Name + " has been unselected")
          unselectedReferenceIdentifier.add(referenceidentifier.ID)
          console.log("is unselected " + unselectedReferenceIdentifier.has(referenceidentifier.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let referenceidentifier = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ReferenceIdentifierDB
      if (unselectedReferenceIdentifier.has(referenceidentifier.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<ReferenceIdentifierDB>) = new Array<ReferenceIdentifierDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          referenceidentifier => {
            if (!this.initialSelection.includes(referenceidentifier)) {
              // console.log("referenceidentifier " + referenceidentifier.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + referenceidentifier.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = referenceidentifier.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = referenceidentifier.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("referenceidentifier " + referenceidentifier.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<ReferenceIdentifierDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
