// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { PkgeltDB } from '../pkgelt-db'
import { PkgeltService } from '../pkgelt.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-pkgeltstable',
  templateUrl: './pkgelts-table.component.html',
  styleUrls: ['./pkgelts-table.component.css'],
})
export class PkgeltsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of Pkgelt instances
  selection: SelectionModel<PkgeltDB>;
  initialSelection = new Array<PkgeltDB>();

  // the data source for the table
  pkgelts: PkgeltDB[];
  matTableDataSource: MatTableDataSource<PkgeltDB>

  // front repo, that will be referenced by this.pkgelts
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (pkgeltDB: PkgeltDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return pkgeltDB.Name;

        case 'Path':
          return pkgeltDB.Path;

        default:
          return PkgeltDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (pkgeltDB: PkgeltDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the pkgeltDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += pkgeltDB.Name.toLowerCase()
      mergedContent += pkgeltDB.Path.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private pkgeltService: PkgeltService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of pkgelt instances
    public dialogRef: MatDialogRef<PkgeltsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.pkgeltService.PkgeltServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getPkgelts()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Path",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Path",
      ]
      this.selection = new SelectionModel<PkgeltDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getPkgelts()
    this.matTableDataSource = new MatTableDataSource(this.pkgelts)
  }

  getPkgelts(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.pkgelts = this.frontRepo.Pkgelts_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.pkgelts.forEach(
            pkgelt => {
              let ID = this.dialogData.ID
              let revPointer = pkgelt[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(pkgelt)
              }
            }
          )
          this.selection = new SelectionModel<PkgeltDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let pkgelt = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(pkgelt)
            }
          }
          this.selection = new SelectionModel<PkgeltDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.pkgelts
      }
    )
  }

  // newPkgelt initiate a new pkgelt
  // create a new Pkgelt objet
  newPkgelt() {
  }

  deletePkgelt(pkgeltID: number, pkgelt: PkgeltDB) {
    // list of pkgelts is truncated of pkgelt before the delete
    this.pkgelts = this.pkgelts.filter(h => h !== pkgelt);

    this.pkgeltService.deletePkgelt(pkgeltID).subscribe(
      pkgelt => {
        this.pkgeltService.PkgeltServiceChanged.next("delete")
      }
    );
  }

  editPkgelt(pkgeltID: number, pkgelt: PkgeltDB) {

  }

  // display pkgelt in router
  displayPkgeltInRouter(pkgeltID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongdoc_go-" + "pkgelt-display", pkgeltID])
  }

  // set editor outlet
  setEditorRouterOutlet(pkgeltID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_editor: ["github_com_fullstack_lang_gongdoc_go-" + "pkgelt-detail", pkgeltID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(pkgeltID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_presentation: ["github_com_fullstack_lang_gongdoc_go-" + "pkgelt-presentation", pkgeltID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.pkgelts.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.pkgelts.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<PkgeltDB>()

      // reset all initial selection of pkgelt that belong to pkgelt
      this.initialSelection.forEach(
        pkgelt => {
          pkgelt[this.dialogData.ReversePointer].Int64 = 0
          pkgelt[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(pkgelt)
        }
      )

      // from selection, set pkgelt that belong to pkgelt
      this.selection.selected.forEach(
        pkgelt => {
          let ID = +this.dialogData.ID
          pkgelt[this.dialogData.ReversePointer].Int64 = ID
          pkgelt[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(pkgelt)
        }
      )

      // update all pkgelt (only update selection & initial selection)
      toUpdate.forEach(
        pkgelt => {
          this.pkgeltService.updatePkgelt(pkgelt)
            .subscribe(pkgelt => {
              this.pkgeltService.PkgeltServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedPkgelt = new Set<number>()
      for (let pkgelt of this.initialSelection) {
        if (this.selection.selected.includes(pkgelt)) {
          // console.log("pkgelt " + pkgelt.Name + " is still selected")
        } else {
          console.log("pkgelt " + pkgelt.Name + " has been unselected")
          unselectedPkgelt.add(pkgelt.ID)
          console.log("is unselected " + unselectedPkgelt.has(pkgelt.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let pkgelt = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedPkgelt.has(pkgelt.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          pkgelt => {
            if (!this.initialSelection.includes(pkgelt)) {
              // console.log("pkgelt " + pkgelt.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + pkgelt.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = pkgelt.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("pkgelt " + pkgelt.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<PkgeltDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
