// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { PkgeltDB } from '../pkgelt-db'
import { PkgeltService } from '../pkgelt.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-pkgeltstable',
  templateUrl: './pkgelts-table.component.html',
  styleUrls: ['./pkgelts-table.component.css'],
})
export class PkgeltsTableComponent implements OnInit {

  // used if the component is called as a selection component of Pkgelt instances
  selection: SelectionModel<PkgeltDB>;
  initialSelection = new Array<PkgeltDB>();

  // the data source for the table
  pkgelts: PkgeltDB[];
  matTableDataSource: MatTableDataSource<PkgeltDB>


  // front repo, that will be referenced by this.pkgelts
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

	// enable sorting on all fields (including pointers and reverse pointer)
	this.matTableDataSource.sortingDataAccessor = (pkgeltDB: PkgeltDB, property: string) => {
		switch (property) {
				// insertion point for specific sorting accessor
			case 'Name':
				return pkgeltDB.Name;

			case 'Path':
				return pkgeltDB.Path;

				default:
					return PkgeltDB[property];
		}
	}; 

	// enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
	this.matTableDataSource.filterPredicate = (pkgeltDB: PkgeltDB, filter: string) => {

		// filtering is based on finding a lower case filter into a concatenated string
		// the pkgeltDB properties
		let mergedContent = ""

		// insertion point for merging of fields
		mergedContent += pkgeltDB.Name.toLowerCase()
		mergedContent += pkgeltDB.Path.toLowerCase()

		let isSelected = mergedContent.includes(filter.toLowerCase())
		return isSelected
	};

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private pkgeltService: PkgeltService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of pkgelt instances
    public dialogRef: MatDialogRef<PkgeltsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.pkgeltService.PkgeltServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getPkgelts()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Path",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Path",
      ]
      this.selection = new SelectionModel<PkgeltDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getPkgelts()
    this.matTableDataSource = new MatTableDataSource(this.pkgelts)
  }

  getPkgelts(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.pkgelts = this.frontRepo.Pkgelts_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.pkgelts.forEach(
            pkgelt => {
              let ID = this.dialogData.ID
              let revPointer = pkgelt[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(pkgelt)
              }
            }
          )
          this.selection = new SelectionModel<PkgeltDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.pkgelts
      }
    )
  }

  // newPkgelt initiate a new pkgelt
  // create a new Pkgelt objet
  newPkgelt() {
  }

  deletePkgelt(pkgeltID: number, pkgelt: PkgeltDB) {
    // list of pkgelts is truncated of pkgelt before the delete
    this.pkgelts = this.pkgelts.filter(h => h !== pkgelt);

    this.pkgeltService.deletePkgelt(pkgeltID).subscribe(
      pkgelt => {
        this.pkgeltService.PkgeltServiceChanged.next("delete")
      }
    );
  }

  editPkgelt(pkgeltID: number, pkgelt: PkgeltDB) {

  }

  // display pkgelt in router
  displayPkgeltInRouter(pkgeltID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongdoc_go-" + "pkgelt-display", pkgeltID])
  }

  // set editor outlet
  setEditorRouterOutlet(pkgeltID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_editor: ["github_com_fullstack_lang_gongdoc_go-" + "pkgelt-detail", pkgeltID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(pkgeltID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_presentation: ["github_com_fullstack_lang_gongdoc_go-" + "pkgelt-presentation", pkgeltID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.pkgelts.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.pkgelts.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<PkgeltDB>()

    // reset all initial selection of pkgelt that belong to pkgelt through Anarrayofb
    this.initialSelection.forEach(
      pkgelt => {
        pkgelt[this.dialogData.ReversePointer].Int64 = 0
        pkgelt[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(pkgelt)
      }
    )

    // from selection, set pkgelt that belong to pkgelt through Anarrayofb
    this.selection.selected.forEach(
      pkgelt => {
        let ID = +this.dialogData.ID
        pkgelt[this.dialogData.ReversePointer].Int64 = ID
        pkgelt[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(pkgelt)
      }
    )

    // update all pkgelt (only update selection & initial selection)
    toUpdate.forEach(
      pkgelt => {
        this.pkgeltService.updatePkgelt(pkgelt)
          .subscribe(pkgelt => {
            this.pkgeltService.PkgeltServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
