// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { StateDB } from '../state-db'
import { StateService } from '../state.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-statestable',
  templateUrl: './states-table.component.html',
  styleUrls: ['./states-table.component.css'],
})
export class StatesTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of State instances
  selection: SelectionModel<StateDB>;
  initialSelection = new Array<StateDB>();

  // the data source for the table
  states: StateDB[];
  matTableDataSource: MatTableDataSource<StateDB>

  // front repo, that will be referenced by this.states
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (stateDB: StateDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return stateDB.Name;

        case 'X':
          return stateDB.X;

        case 'Y':
          return stateDB.Y;

        case 'States':
          return this.frontRepo.Umlscs.get(stateDB.Umlsc_StatesDBID.Int64)?.Name;

        default:
          return StateDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (stateDB: StateDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the stateDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += stateDB.Name.toLowerCase()
      mergedContent += stateDB.X.toString()
      mergedContent += stateDB.Y.toString()
      if (stateDB.Umlsc_StatesDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Umlscs.get(stateDB.Umlsc_StatesDBID.Int64)?.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private stateService: StateService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of state instances
    public dialogRef: MatDialogRef<StatesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.stateService.StateServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getStates()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "X",
        "Y",
        "States",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "X",
        "Y",
        "States",
      ]
      this.selection = new SelectionModel<StateDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getStates()
    this.matTableDataSource = new MatTableDataSource(this.states)
  }

  getStates(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.states = this.frontRepo.States_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.states.forEach(
            state => {
              let ID = this.dialogData.ID
              let revPointer = state[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(state)
              }
            }
          )
          this.selection = new SelectionModel<StateDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let state = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(state)
            }
          }
          this.selection = new SelectionModel<StateDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.states
      }
    )
  }

  // newState initiate a new state
  // create a new State objet
  newState() {
  }

  deleteState(stateID: number, state: StateDB) {
    // list of states is truncated of state before the delete
    this.states = this.states.filter(h => h !== state);

    this.stateService.deleteState(stateID).subscribe(
      state => {
        this.stateService.StateServiceChanged.next("delete")
      }
    );
  }

  editState(stateID: number, state: StateDB) {

  }

  // display state in router
  displayStateInRouter(stateID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongdoc_go-" + "state-display", stateID])
  }

  // set editor outlet
  setEditorRouterOutlet(stateID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_editor: ["github_com_fullstack_lang_gongdoc_go-" + "state-detail", stateID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(stateID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_presentation: ["github_com_fullstack_lang_gongdoc_go-" + "state-presentation", stateID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.states.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.states.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<StateDB>()

      // reset all initial selection of state that belong to state
      this.initialSelection.forEach(
        state => {
          state[this.dialogData.ReversePointer].Int64 = 0
          state[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(state)
        }
      )

      // from selection, set state that belong to state
      this.selection.selected.forEach(
        state => {
          let ID = +this.dialogData.ID
          state[this.dialogData.ReversePointer].Int64 = ID
          state[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(state)
        }
      )

      // update all state (only update selection & initial selection)
      toUpdate.forEach(
        state => {
          this.stateService.updateState(state)
            .subscribe(state => {
              this.stateService.StateServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedState = new Set<number>()
      for (let state of this.initialSelection) {
        if (this.selection.selected.includes(state)) {
          // console.log("state " + state.Name + " is still selected")
        } else {
          console.log("state " + state.Name + " has been unselected")
          unselectedState.add(state.ID)
          console.log("is unselected " + unselectedState.has(state.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let state = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedState.has(state.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          state => {
            if (!this.initialSelection.includes(state)) {
              // console.log("state " + state.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + state.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = state.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("state " + state.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<StateDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
