// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { GongShapeDB } from '../gongshape-db'
import { GongShapeService } from '../gongshape.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-gongshapestable',
  templateUrl: './gongshapes-table.component.html',
  styleUrls: ['./gongshapes-table.component.css'],
})
export class GongShapesTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of GongShape instances
  selection: SelectionModel<GongShapeDB> = new (SelectionModel)
  initialSelection = new Array<GongShapeDB>()

  // the data source for the table
  gongshapes: GongShapeDB[] = []
  matTableDataSource: MatTableDataSource<GongShapeDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.gongshapes
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (gongshapeDB: GongShapeDB, property: string) => {
      switch (property) {
        case 'ID':
          return gongshapeDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return gongshapeDB.Name;

        case 'Position':
          return (gongshapeDB.Position ? gongshapeDB.Position.Name : '');

        case 'Identifier':
          return gongshapeDB.Identifier;

        case 'ShowNbInstances':
          return gongshapeDB.ShowNbInstances ? "true" : "false";

        case 'NbInstances':
          return gongshapeDB.NbInstances;

        case 'Width':
          return gongshapeDB.Width;

        case 'Heigth':
          return gongshapeDB.Heigth;

        case 'IsSelected':
          return gongshapeDB.IsSelected ? "true" : "false";

        case 'Classdiagram_GongStructShapes':
          if (this.frontRepo.Classdiagrams.get(gongshapeDB.Classdiagram_GongStructShapesDBID.Int64) != undefined) {
            return this.frontRepo.Classdiagrams.get(gongshapeDB.Classdiagram_GongStructShapesDBID.Int64)!.Name
          } else {
            return ""
          }

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (gongshapeDB: GongShapeDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the gongshapeDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += gongshapeDB.Name.toLowerCase()
      if (gongshapeDB.Position) {
        mergedContent += gongshapeDB.Position.Name.toLowerCase()
      }
      mergedContent += gongshapeDB.Identifier.toLowerCase()
      mergedContent += gongshapeDB.NbInstances.toString()
      mergedContent += gongshapeDB.Width.toString()
      mergedContent += gongshapeDB.Heigth.toString()
      if (gongshapeDB.Classdiagram_GongStructShapesDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Classdiagrams.get(gongshapeDB.Classdiagram_GongStructShapesDBID.Int64)!.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private gongshapeService: GongShapeService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of gongshape instances
    public dialogRef: MatDialogRef<GongShapesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.gongshapeService.GongShapeServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getGongShapes()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "Position",
        "Identifier",
        "ShowNbInstances",
        "NbInstances",
        "Width",
        "Heigth",
        "IsSelected",
        "Classdiagram_GongStructShapes",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Position",
        "Identifier",
        "ShowNbInstances",
        "NbInstances",
        "Width",
        "Heigth",
        "IsSelected",
        "Classdiagram_GongStructShapes",
      ]
      this.selection = new SelectionModel<GongShapeDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getGongShapes()

    this.matTableDataSource = new MatTableDataSource(this.gongshapes)
  }

  getGongShapes(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.gongshapes = this.frontRepo.GongShapes_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let gongshape of this.gongshapes) {
            let ID = this.dialogData.ID
            let revPointer = gongshape[this.dialogData.ReversePointer as keyof GongShapeDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(gongshape)
            }
            this.selection = new SelectionModel<GongShapeDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, GongShapeDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to GongShapeDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as GongShapeDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let gongshape = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as GongShapeDB
              this.initialSelection.push(gongshape)
            }
          }

          this.selection = new SelectionModel<GongShapeDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.gongshapes
      }
    )
  }

  // newGongShape initiate a new gongshape
  // create a new GongShape objet
  newGongShape() {
  }

  deleteGongShape(gongshapeID: number, gongshape: GongShapeDB) {
    // list of gongshapes is truncated of gongshape before the delete
    this.gongshapes = this.gongshapes.filter(h => h !== gongshape);

    this.gongshapeService.deleteGongShape(gongshapeID, this.GONG__StackPath).subscribe(
      gongshape => {
        this.gongshapeService.GongShapeServiceChanged.next("delete")
      }
    );
  }

  editGongShape(gongshapeID: number, gongshape: GongShapeDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(gongshapeID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "gongshape" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, gongshapeID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.gongshapes.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.gongshapes.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<GongShapeDB>()

      // reset all initial selection of gongshape that belong to gongshape
      for (let gongshape of this.initialSelection) {
        let index = gongshape[this.dialogData.ReversePointer as keyof GongShapeDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(gongshape)

      }

      // from selection, set gongshape that belong to gongshape
      for (let gongshape of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = gongshape[this.dialogData.ReversePointer as keyof GongShapeDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(gongshape)
      }


      // update all gongshape (only update selection & initial selection)
      for (let gongshape of toUpdate) {
        this.gongshapeService.updateGongShape(gongshape, this.GONG__StackPath)
          .subscribe(gongshape => {
            this.gongshapeService.GongShapeServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, GongShapeDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedGongShape = new Set<number>()
      for (let gongshape of this.initialSelection) {
        if (this.selection.selected.includes(gongshape)) {
          // console.log("gongshape " + gongshape.Name + " is still selected")
        } else {
          console.log("gongshape " + gongshape.Name + " has been unselected")
          unselectedGongShape.add(gongshape.ID)
          console.log("is unselected " + unselectedGongShape.has(gongshape.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let gongshape = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as GongShapeDB
      if (unselectedGongShape.has(gongshape.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<GongShapeDB>) = new Array<GongShapeDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          gongshape => {
            if (!this.initialSelection.includes(gongshape)) {
              // console.log("gongshape " + gongshape.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + gongshape.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = gongshape.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = gongshape.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("gongshape " + gongshape.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<GongShapeDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
