// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { StateDB } from '../state-db'
import { StateService } from '../state.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-state-sorting',
  templateUrl: './state-sorting.component.html',
  styleUrls: ['./state-sorting.component.css']
})
export class StateSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of State instances that are in the association
  associatedStates = new Array<StateDB>();

  constructor(
    private stateService: StateService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of state instances
    public dialogRef: MatDialogRef<StateSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getStates()
  }

  getStates(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let state of this.frontRepo.States_array) {
          let ID = this.dialogData.ID
          let revPointerID = state[this.dialogData.ReversePointer]
          let revPointerID_Index = state[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedStates.push(state)
          }
        }

        // sort associated state according to order
        this.associatedStates.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedStates, event.previousIndex, event.currentIndex);

    // set the order of State instances
    let index = 0
    
    for (let state of this.associatedStates) {
      let revPointerID_Index = state[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedStates.forEach(
      state => {
        this.stateService.updateState(state)
          .subscribe(state => {
            this.stateService.StateServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
