// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { GongdocStatusDB } from '../gongdocstatus-db'
import { GongdocStatusService } from '../gongdocstatus.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-gongdocstatus-sorting',
  templateUrl: './gongdocstatus-sorting.component.html',
  styleUrls: ['./gongdocstatus-sorting.component.css']
})
export class GongdocStatusSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of GongdocStatus instances that are in the association
  associatedGongdocStatuss = new Array<GongdocStatusDB>();

  constructor(
    private gongdocstatusService: GongdocStatusService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of gongdocstatus instances
    public dialogRef: MatDialogRef<GongdocStatusSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getGongdocStatuss()
  }

  getGongdocStatuss(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let gongdocstatus of this.frontRepo.GongdocStatuss_array) {
          let ID = this.dialogData.ID
          let revPointerID = gongdocstatus[this.dialogData.ReversePointer]
          let revPointerID_Index = gongdocstatus[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedGongdocStatuss.push(gongdocstatus)
          }
        }

        // sort associated gongdocstatus according to order
        this.associatedGongdocStatuss.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedGongdocStatuss, event.previousIndex, event.currentIndex);

    // set the order of GongdocStatus instances
    let index = 0
    
    for (let gongdocstatus of this.associatedGongdocStatuss) {
      let revPointerID_Index = gongdocstatus[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedGongdocStatuss.forEach(
      gongdocstatus => {
        this.gongdocstatusService.updateGongdocStatus(gongdocstatus)
          .subscribe(gongdocstatus => {
            this.gongdocstatusService.GongdocStatusServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
