// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { UmlscDB } from '../umlsc-db'
import { UmlscService } from '../umlsc.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-umlscstable',
  templateUrl: './umlscs-table.component.html',
  styleUrls: ['./umlscs-table.component.css'],
})
export class UmlscsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of Umlsc instances
  selection: SelectionModel<UmlscDB>;
  initialSelection = new Array<UmlscDB>();

  // the data source for the table
  umlscs: UmlscDB[];
  matTableDataSource: MatTableDataSource<UmlscDB>

  // front repo, that will be referenced by this.umlscs
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (umlscDB: UmlscDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return umlscDB.Name;

        case 'Activestate':
          return umlscDB.Activestate;

        case 'Pkgelt_Umlscs':
          return this.frontRepo.Pkgelts.get(umlscDB.Pkgelt_UmlscsDBID.Int64)?.Name;

        default:
          return UmlscDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (umlscDB: UmlscDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the umlscDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += umlscDB.Name.toLowerCase()
      mergedContent += umlscDB.Activestate.toLowerCase()
      if (umlscDB.Pkgelt_UmlscsDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Pkgelts.get(umlscDB.Pkgelt_UmlscsDBID.Int64)?.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private umlscService: UmlscService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of umlsc instances
    public dialogRef: MatDialogRef<UmlscsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.umlscService.UmlscServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getUmlscs()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Activestate",
        "Pkgelt_Umlscs",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Activestate",
        "Pkgelt_Umlscs",
      ]
      this.selection = new SelectionModel<UmlscDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getUmlscs()
    this.matTableDataSource = new MatTableDataSource(this.umlscs)
  }

  getUmlscs(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.umlscs = this.frontRepo.Umlscs_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.umlscs.forEach(
            umlsc => {
              let ID = this.dialogData.ID
              let revPointer = umlsc[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(umlsc)
              }
            }
          )
          this.selection = new SelectionModel<UmlscDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let umlsc = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(umlsc)
            }
          }
          this.selection = new SelectionModel<UmlscDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.umlscs
      }
    )
  }

  // newUmlsc initiate a new umlsc
  // create a new Umlsc objet
  newUmlsc() {
  }

  deleteUmlsc(umlscID: number, umlsc: UmlscDB) {
    // list of umlscs is truncated of umlsc before the delete
    this.umlscs = this.umlscs.filter(h => h !== umlsc);

    this.umlscService.deleteUmlsc(umlscID).subscribe(
      umlsc => {
        this.umlscService.UmlscServiceChanged.next("delete")
      }
    );
  }

  editUmlsc(umlscID: number, umlsc: UmlscDB) {

  }

  // display umlsc in router
  displayUmlscInRouter(umlscID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongdoc_go-" + "umlsc-display", umlscID])
  }

  // set editor outlet
  setEditorRouterOutlet(umlscID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_editor: ["github_com_fullstack_lang_gongdoc_go-" + "umlsc-detail", umlscID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(umlscID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongdoc_go_presentation: ["github_com_fullstack_lang_gongdoc_go-" + "umlsc-presentation", umlscID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.umlscs.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.umlscs.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<UmlscDB>()

      // reset all initial selection of umlsc that belong to umlsc
      this.initialSelection.forEach(
        umlsc => {
          umlsc[this.dialogData.ReversePointer].Int64 = 0
          umlsc[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(umlsc)
        }
      )

      // from selection, set umlsc that belong to umlsc
      this.selection.selected.forEach(
        umlsc => {
          let ID = +this.dialogData.ID
          umlsc[this.dialogData.ReversePointer].Int64 = ID
          umlsc[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(umlsc)
        }
      )

      // update all umlsc (only update selection & initial selection)
      toUpdate.forEach(
        umlsc => {
          this.umlscService.updateUmlsc(umlsc)
            .subscribe(umlsc => {
              this.umlscService.UmlscServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedUmlsc = new Set<number>()
      for (let umlsc of this.initialSelection) {
        if (this.selection.selected.includes(umlsc)) {
          // console.log("umlsc " + umlsc.Name + " is still selected")
        } else {
          console.log("umlsc " + umlsc.Name + " has been unselected")
          unselectedUmlsc.add(umlsc.ID)
          console.log("is unselected " + unselectedUmlsc.has(umlsc.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let umlsc = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedUmlsc.has(umlsc.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          umlsc => {
            if (!this.initialSelection.includes(umlsc)) {
              // console.log("umlsc " + umlsc.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + umlsc.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = umlsc.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("umlsc " + umlsc.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<UmlscDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
