// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ReferenceIdentifierDB } from './referenceidentifier-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class ReferenceIdentifierService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ReferenceIdentifierServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private referenceidentifiersUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.referenceidentifiersUrl = origin + '/api/github.com/fullstack-lang/gongdoc/go/v1/referenceidentifiers';
  }

  /** GET referenceidentifiers from the server */
  getReferenceIdentifiers(): Observable<ReferenceIdentifierDB[]> {
    return this.http.get<ReferenceIdentifierDB[]>(this.referenceidentifiersUrl)
      .pipe(
        tap(_ => this.log('fetched referenceidentifiers')),
        catchError(this.handleError<ReferenceIdentifierDB[]>('getReferenceIdentifiers', []))
      );
  }

  /** GET referenceidentifier by id. Will 404 if id not found */
  getReferenceIdentifier(id: number): Observable<ReferenceIdentifierDB> {
    const url = `${this.referenceidentifiersUrl}/${id}`;
    return this.http.get<ReferenceIdentifierDB>(url).pipe(
      tap(_ => this.log(`fetched referenceidentifier id=${id}`)),
      catchError(this.handleError<ReferenceIdentifierDB>(`getReferenceIdentifier id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new referenceidentifier to the server */
  postReferenceIdentifier(referenceidentifierdb: ReferenceIdentifierDB): Observable<ReferenceIdentifierDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<ReferenceIdentifierDB>(this.referenceidentifiersUrl, referenceidentifierdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted referenceidentifierdb id=${referenceidentifierdb.ID}`)
      }),
      catchError(this.handleError<ReferenceIdentifierDB>('postReferenceIdentifier'))
    );
  }

  /** DELETE: delete the referenceidentifierdb from the server */
  deleteReferenceIdentifier(referenceidentifierdb: ReferenceIdentifierDB | number): Observable<ReferenceIdentifierDB> {
    const id = typeof referenceidentifierdb === 'number' ? referenceidentifierdb : referenceidentifierdb.ID;
    const url = `${this.referenceidentifiersUrl}/${id}`;

    return this.http.delete<ReferenceIdentifierDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted referenceidentifierdb id=${id}`)),
      catchError(this.handleError<ReferenceIdentifierDB>('deleteReferenceIdentifier'))
    );
  }

  /** PUT: update the referenceidentifierdb on the server */
  updateReferenceIdentifier(referenceidentifierdb: ReferenceIdentifierDB): Observable<ReferenceIdentifierDB> {
    const id = typeof referenceidentifierdb === 'number' ? referenceidentifierdb : referenceidentifierdb.ID;
    const url = `${this.referenceidentifiersUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<ReferenceIdentifierDB>(url, referenceidentifierdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated referenceidentifierdb id=${referenceidentifierdb.ID}`)
      }),
      catchError(this.handleError<ReferenceIdentifierDB>('updateReferenceIdentifier'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
