// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { ReferenceIdentifierDB } from '../referenceidentifier-db'
import { ReferenceIdentifierService } from '../referenceidentifier.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-referenceidentifier-sorting',
  templateUrl: './referenceidentifier-sorting.component.html',
  styleUrls: ['./referenceidentifier-sorting.component.css']
})
export class ReferenceIdentifierSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of ReferenceIdentifier instances that are in the association
  associatedReferenceIdentifiers = new Array<ReferenceIdentifierDB>();

  constructor(
    private referenceidentifierService: ReferenceIdentifierService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of referenceidentifier instances
    public dialogRef: MatDialogRef<ReferenceIdentifierSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getReferenceIdentifiers()
  }

  getReferenceIdentifiers(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let referenceidentifier of this.frontRepo.ReferenceIdentifiers_array) {
          let ID = this.dialogData.ID
          let revPointerID = referenceidentifier[this.dialogData.ReversePointer as keyof ReferenceIdentifierDB] as unknown as NullInt64
          let revPointerID_Index = referenceidentifier[this.dialogData.ReversePointer + "_Index" as keyof ReferenceIdentifierDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedReferenceIdentifiers.push(referenceidentifier)
          }
        }

        // sort associated referenceidentifier according to order
        this.associatedReferenceIdentifiers.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedReferenceIdentifiers, event.previousIndex, event.currentIndex);

    // set the order of ReferenceIdentifier instances
    let index = 0

    for (let referenceidentifier of this.associatedReferenceIdentifiers) {
      let revPointerID_Index = referenceidentifier[this.dialogData.ReversePointer + "_Index" as keyof ReferenceIdentifierDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedReferenceIdentifiers.forEach(
      referenceidentifier => {
        this.referenceidentifierService.updateReferenceIdentifier(referenceidentifier)
          .subscribe(referenceidentifier => {
            this.referenceidentifierService.ReferenceIdentifierServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
